apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-fs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"