name: Wicked Prototype Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Maven Package
        run: mvn -B clean spring-boot:build-image
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Publish Docker image neo4j
        run: docker push ice0nine/wickedenterprise-dlt:neo4j-writer
      - name: Publish Docker image rdbms
        run: docker push ice0nine/wickedenterprise-dlt:rdbms-writer
      - name: Publish Docker image listener
        run: docker push ice0nine/wickedenterprise-dlt:blockchain-listener